[package]
name = "lsig"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
sha256= "1.5.0"
num-bigint= "0.4.4"
